### ISSUE TITLE
UNEXPECTED TOP-LEVEL EXCEPTION

### ISSUE THREAD

**Issue by TGNC-dev** [floatinghotpot/cordova-admob-pro#164]
Hi,

I can not build my app once I install this plugin. I tried uninstalling all other plugins, but it is always once i install this one this error appear.

Here is the log

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

:dexRelease FAILED

Thanks by advance ^^

**Comment by hotgeart** [comment]
Same here

**Comment by floatinghotpot** [comment]
Caused by duplicated google-play-services.jar.

This plugin properly referenced to the google-play-services.jar in your android sdk with tag framework , which is recommended by Google team.

While some other plugins contains the jar, or depends on a plugin named com.google.playservices which is already deprecated.

Please list all plugins and check which plugin use it improperly.

**Comment by TGNC-dev** [comment]
Hi, Thank you for the answer.

It seems indeed that finally this plugin: https://github.com/danwilson/google-analytics-plugin is causing the troubles as it depends on com.google.playservices.

I absolutely have to use that plugin, so can you just explain me how should it be fix? (or if you have a link to a documentation that explains good practices to dev cordova plugins)

Thank you by advance!

**Comment by floatinghotpot** [comment]
Report a bug report to that plugin or fork to change it yourself.

Should change the dependency in plugin.xml to framework tag, as suggested by author of com.google.playservices.

**Comment by TGNC-dev** [comment]
Okay thank your your answer.

I will fork the plugins causing problems and push the fixes.
