### ISSUE TITLE
Cannot find "cordova-plugin-admobpro" via plugin registry

### ISSUE THREAD

**Issue by ctl1690** [floatinghotpot/cordova-admob-pro#165]
Two exceptions:

1. cordova plugin add node_modules/cordova-plugin-admobpro/
Installing "cordova-plugin-admobpro" for android
Fetching plugin "cordova-plugin-extension" via plugin registry
Failed to install 'cordova-plugin-admobpro':Error: 404 Not Found: cordova-plugin-extension
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
  

2. Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-admobpro':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:106:31)

**Comment by floatinghotpot** [comment]
You are using a old version of Cordova, please upgrade your cordova CLI to v5.x
```bash
[sudo] npm install -g cordova
```
