### ISSUE TITLE
Plugin fails to install

### ISSUE THREAD

**Issue by arcadiogarcia** [floatinghotpot/cordova-admob-pro#172]
I'm trying to install this plugin (I have successfully installed others) but I encounter this error:

>cordova plugin add cordova-plugin-admobpro

npm http GET https://registry.npmjs.org/cordova-plugin-admobpro
npm http 304 https://registry.npmjs.org/cordova-plugin-admobpro
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-admobpro':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at Object.module.exports.framework.install (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
    at installWrapper (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:550:20)
    at C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:342:28
    at _fulfilled (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at Object.module.exports.framework.install (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
    at installWrapper (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:550:20)
    at C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:342:28
    at _fulfilled (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Arcadio\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49

It seems to be a problem resolving some path needed when installing the plugin for Android, but as I said other plugins installed without problems. The path that fails is adquired with "getProjectSdkDir(project_dir)": it returns undefined even if project_dir has the right value(C:\Users\Arcadio\Documents\GitHub\PhoneKeyboard\phone\cordova\keystroke\Keystroke\platforms\android).

**Comment by floatinghotpot** [comment]
npm cache clean
rm -r ~/.plugman

cordova plugin add Cordova-plugin-admobpro

**Comment by arcadiogarcia** [comment]
Still no luck, I get the same error. It seems that my platforms\android\local.properties does not contain the sdk.dir value that plugman is looking for. So probably a Cordova error, thanks for your help!
