### ISSUE TITLE
Crashes on Note4

### ISSUE THREAD

**Issue by t-nonque** [floatinghotpot/cordova-admob-pro#187]
Hi,

I got some crash reports on my play store console, here are the logs:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
at com.rjfun.cordova.ad.GenericAdPlugin$3.run(GenericAdPlugin.java:383)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5944)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

As the GenericAdPlugin.java code is not public, i have no clue where that error comes from.

Thanks by advance

**Comment by floatinghotpot** [comment]
Are you using crosswalk or other plugins? Which version of Cordova and android?

**Comment by t-nonque** [comment]
Hi, Yes i am using crosswalk.

**Comment by floatinghotpot** [comment]
Crosswalk changed the Cordova webview, so it will cause some trouble. Will look into the issue, to see whether it's possible to get it working with crosswalk or not.

**Comment by floatinghotpot** [comment]
Please discuss and follow up in issue #171, same reason.
