### ISSUE TITLE
prepareInterstitial always fails with "Class not found" error message

### ISSUE THREAD

**Issue by kingkrausel** [floatinghotpot/cordova-admob-pro#227]
I am using the cordova-admob-pro plugin for an amazon-fireos cordova app. When executing the following code, the fail callback is always called with "Class not found" as first parameter:

```javascript
if(AdMob) AdMob.prepareInterstitial( {adId:admobid.interstitial, autoShow:false}, function(){
        console.log('succ!');
    }, function(a){
        console.log('fail: ' + JSON.stringify(a)); //fail: "Class not found"
    } );
```
admobid.interstitial is set correctly.

**Comment by floatinghotpot** [comment]
This plugin only support ios / android / wp8

Though amazon-fireos is a derivative of android, I am not sure whether it can be supported or not. 

You can try:
download the plugin, open plugin.xml, copy the section android to amazon-fireos, then add to your project from local copy.

**Comment by kingkrausel** [comment]
I tried what you said, but it fails with the following error:
```
Installing "cordova-plugin-admobpro" for amazon-fireos
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-admobpro':Error: Uh oh!
ENOENT, no such file or directory 'C:\Users\denis_000\Documents\BitBucket\quizbattle\build\platforms\amazon-fireos\local.properties'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.createEditor (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\properties-parser\index.js:328:39)
    at Object.module.exports.getProjectSdkDir (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\amazon-fireos.js:164:49)
    at Object.module.exports.framework.install (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\amazon-fireos.js:112:46)
    at installWrapper (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:576:20)
    at C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:363:28
Error: Uh oh!
ENOENT, no such file or directory 'C:\Users\denis_000\Documents\BitBucket\quizbattle\build\platforms\amazon-fireos\local.properties'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.createEditor (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\properties-parser\index.js:328:39)
    at Object.module.exports.getProjectSdkDir (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\amazon-fireos.js:164:49)
    at Object.module.exports.framework.install (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\amazon-fireos.js:112:46)
    at installWrapper (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:576:20)
    at C:\Users\denis_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:363:28

```

Maybe this error occurs because of the dependency 'cordova-plugin-extension'?  I tried to install it separately from a local copy where I also added the amazon-fireos platform in the plugin.xml. However, it seems that cordova ignores the installed plugin and tries to install it from npm. Which leads to the same problem. Any suggestions?

**Comment by floatinghotpot** [comment]
Now I am looking into it. 

I found that the different is: building android platform is using gradle now, but building amazon-fireos is still using ant, so it cannot correctly handle ```<framework>``` tag. I will create a section for amazon-fireos, once tested pass, will publish to npm. 

Stay tuned.

**Comment by kingkrausel** [comment]
Thank you for you effort!

**Comment by floatinghotpot** [comment]
It's done and I've tested it on simulator and update the published plugins. You can try it on real device.

```bash
cordova platform add amazon-fireos
cordova plugin add cordova-plugin-admobpro
```

as you know, to build cordova apps for fireos, the amazon sdk is required, download it here:
https://s3.amazonaws.com/awv-api/awv_api.zip

before build, remember to copy the two files from amazon webview api sdk to platforms\amazon-fireos\libs:
```
awv_android_factory.jar
awv_interface.jar
```

Please test on real fireos device, and give me feedback. Good luck!

**Comment by kingkrausel** [comment]
I installed the updated plugin and successfully build the amazon-fireos app. I used the following code to test an interstitial and a banner ad:
````javascript
AdMob.prepareInterstitial({
        adId: admobid.interstitial,
        autoShow: true
    },function(a){
        console.log('MOBILE-ADS/AdMob: suc');
    },function(a){
        console.log('MOBILE-ADS/AdMob: fail '+ JSON.stringify(a));
    });

    console.log('ADMob creating banner ad...');
    AdMob.createBanner({
        adId: admobid.banner,
        position: AdMob.AD_POSITION.BOTTOM_CENTER,
        autoShow: true,
        success: function(){
            console.log('AdMob:banner suc');
        },
        error: function(){
            console.log('AdMob:failed to create banner');
        }
    });
````
At first sight, this seemed to work, since the ads were displayed. However, I took a look at the ADB log found some errors which cause (as far as I understand it) the plugin to use fallback/test ads. Here are some important lines of the log:
````
D/PluginManager( 3096): in getPlugin for service - AdMob

D/GenericAdPlugin( 3096): prepareInterstitial: ca-app-pub-/*My-Interstitial-id*/, true

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x079c at 0x83 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.a

D/PluginManager( 3096): in getPlugin for service - AdMob

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x0797 at 0x8e in Lcom/google/android/gms/common/GooglePlayServicesUtil;.a

D/GenericAdPlugin( 3096): createBanner: ca-app-pub-/*My-banner-id*/, true

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07ab at 0x99 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.a

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a8 at 0xab in Lcom/google/android/gms/common/GooglePlayServicesUtil;.a

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a1 at 0xbd in Lcom/google/android/gms/common/GooglePlayServicesUtil;.a

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x079e at 0xe7 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.a

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a8 at 0x106 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.a

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a5 at 0x07 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.d

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x079b at 0x18 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.d

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x079a at 0x1f in Lcom/google/android/gms/common/GooglePlayServicesUtil;.d

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x0796 at 0x26 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.d

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07aa at 0x2d in Lcom/google/android/gms/common/GooglePlayServicesUtil;.d

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a7 at 0x34 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.d

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a0 at 0x3b in Lcom/google/android/gms/common/GooglePlayServicesUtil;.d

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x079d at 0x42 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.d

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a6 at 0x49 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.d

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x0799 at 0x0f in Lcom/google/android/gms/common/GooglePlayServicesUtil;.e

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x0795 at 0x16 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.e

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a9 at 0x1d in Lcom/google/android/gms/common/GooglePlayServicesUtil;.e

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a5 at 0x07 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.f

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a2 at 0x0e in Lcom/google/android/gms/common/GooglePlayServicesUtil;.f

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a3 at 0x15 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.f

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x079f at 0x1c in Lcom/google/android/gms/common/GooglePlayServicesUtil;.f

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a7 at 0x23 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.f

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a0 at 0x2a in Lcom/google/android/gms/common/GooglePlayServicesUtil;.f

D/PluginManager( 3096): in getPlugin for service - AmazonMobileAdsPlugin

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x079d at 0x31 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.f

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a6 at 0x38 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.f

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a5 at 0x0d in Lcom/google/android/gms/common/GooglePlayServicesUtil;.isGooglePlayServicesAvailable

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x07a4 at 0x05 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.showErrorNotification

I/dalvikvm( 3096): DexOpt: unable to optimize static field ref 0x0798 at 0x25 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.showErrorNotification

E/GooglePlayServicesUtil( 3096): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

W/GooglePlayServicesUtil( 3096): Google Play services is missing.

I/Ads     ( 3096): Starting ad request.

I/Ads     ( 3096): Use AdRequest.Builder.addTestDevice("E135E2BA1B854E77DD3A1E88A5A7D949") to get test ads on this device.


...


D/CordovaLog( 3096): file:///android_asset/www/app.entry.bundle.js: Line 38598 : ADMob creating banner ad...

I/chromium( 3096): [INFO:CONSOLE(38598)] "ADMob creating banner ad..."

D/GenericAdPlugin( 3096): cordova-android 3.x, webview in linearlayout

E/GooglePlayServicesUtil( 3096): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

W/GooglePlayServicesUtil( 3096): Google Play services is missing.

D/PluginManager( 3096): in getPlugin for service - App

I/App     ( 3096): WARNING: Back Button Default Behavior will be overridden.  The backbutton event will be fired!

I/Ads     ( 3096): Starting ad request.

I/Ads     ( 3096): Use AdRequest.Builder.addTestDevice("E135E2BA1B854E77DD3A1E88A5A7D949") to get test ads on this device.


...


D/CordovaLog( 3096): file:///android_asset/www/app.entry.bundle.js: Line 38585 : MOBILE-ADS/AdMob: fail "Error"

I/chromium( 3096): [INFO:CONSOLE(38585)] "MOBILE-ADS/AdMob: fail "Error""

````

Are the displayed ads just test-ads or the "real" ones? I also don't see any changes on my AdMob reporting.
I also noticed that ```` AdMob.isInterstitialReady ```` results in this error: ```` Uncaught TypeError: undefined is not a function ````.

**Comment by floatinghotpot** [comment]
Remember to test it on your real device instead of the emulator. Can you paste a screenshot?  

If you see your adId in the log, then the plugin is using your ad instead of fallback/test ad. 

AdMob.isInterstitialReady() is removed, so do not use it.

**Comment by kingkrausel** [comment]
Thank you very much, the correct ids are in the log, and my AdMob statistics were updated accordingly. So everything works. I successfully tested the plugin on the Amazon  Fire TV Stick.
![screen](https://cloud.githubusercontent.com/assets/2597979/10133137/5ffebf50-65db-11e5-8c13-65219fc61f44.png)
