### ISSUE TITLE
Cordova admob pro installation failed

### ISSUE THREAD

**Issue by lordlaw** [floatinghotpot/cordova-admob-pro#239]
i had cordova 5.3.3
Here is the error message

Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-admobpro':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at Object.module.exports.framework.install (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
    at installWrapper (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:576:20)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:363:28
    at _fulfilled (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at Object.module.exports.framework.install (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
    at installWrapper (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:576:20)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:363:28
    at _fulfilled (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49

help needed.

Thanks.

**Comment by floatinghotpot** [comment]
I notice that you are running it under windows. Do you have android SDK and gradle installed? If no, use plugin id "cordova-plugin-admob" instead.

**Comment by floatinghotpot** [comment]
in fact, I can correct install the plugin under windows. here is the steps:
```bash
cordova create test com.rjfun.test Test
cd test
cordova platform add android
cordova plugin add cordova-plugin-admobpro
```

Do you have the cordova CLI correctly installed? If not, try:
* download and install the most recent nodejs from: http://nodejs.org
* upgrade cordova: npm -g install cordova

**Comment by lordlaw** [comment]
Thanks,
with upgrade to latest Nodejs

it works now......
