### ISSUE TITLE
LoadInterstitial: RuntimeException at  android.os.Parcel.readValue

### ISSUE THREAD

**Issue by becvert** [floatinghotpot/cordova-admob-pro#262]
Hello.
I'd like to report an exception that appears in my Google Play Developer Console.
I believe it's linked with the obfuscation process.
(Android 5.0, HTC Desire 820)
Regards

java.lang.RuntimeException: Parcel android.os.Parcel@3c32ed23: Unmarshalling unknown type code 7274595 at offset 12
	at android.os.Parcel.readValue(Parcel.java:2231)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2488)
	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
	at android.os.BaseBundle.keySet(BaseBundle.java:321)
	at com.google.android.gms.ads.internal.i.v.a(SourceFile:136)
	at com.google.android.gms.ads.internal.i.v.<init>(SourceFile:29)
	at com.google.android.gms.ads.internal.i.y.<init>(SourceFile:56)
	at com.google.android.gms.ads.internal.i.y.<init>(SourceFile:65)
	at com.google.android.gms.ads.l.a(SourceFile:73)
	at com.google.android.gms.ads.AdManagerCreatorImpl.a(SourceFile:99)
	at com.google.android.gms.ads.internal.client.ad.onTransact(SourceFile:91)
	at android.os.Binder.transact(Binder.java:380)
	at com.google.android.gms.ads.internal.client.zzt$zza$zza.zza(Unknown Source)
	at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
	at com.google.android.gms.ads.internal.client.zze.zzb(Unknown Source)
	at com.google.android.gms.ads.internal.client.zzaa.zzM(Unknown Source)
	at com.google.android.gms.ads.internal.client.zzaa.zza(Unknown Source)
	at com.google.android.gms.ads.InterstitialAd.loadAd(Unknown Source)
	at com.rjfun.cordova.admob.AdMobPlugin.__loadInterstitial(AdMobPlugin.java:203)
	at com.rjfun.cordova.ad.GenericAdPlugin$5.run(GenericAdPlugin.java:547)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5689)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by floatinghotpot** [comment]
Suggested:
1. double check you are passing right arguments.
2. It's recommended to update to most recent version, v2.11.1.

Here is a simple tool to verify the plugin in your environment with a simple demo project automatically:
```bash
[sudo] npm install -g plugin-verify
plugin-verify cordova-plugin-admobpro android
```

**Comment by floatinghotpot** [comment]
As I did not see further follow up info, I'd like to close this issue tracker. If you can still re-produce it, please re-open this issue tracker with more details.
