### ISSUE TITLE
Meteor Issue Error: 404 Not Found:

### ISSUE THREAD

**Issue by kylepierce** [floatinghotpot/cordova-admob-pro#264]
I am having trouble installing the plugin to my meteor cordova app. I have updated my node, npm, and cordova (5.0) and I still am having trouble getting the app to recognize the plugin. 

meteor add cordova:cordova-plugin-admobpro@2.9.9

meteor build ios-device --server 192.168.0.13:3000  --mobile-settings settings.json

```
Error while building for mobile platforms: Error running                           
/Users/Kyle/.meteor/packages/meteor-tool/.1.1.4.ywf07c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error: 404 Not Found: cordova-plugin-admobpro
at RegClient.<anonymous>
(/Users/Kyle/.meteor/packages/meteor-tool/.1.1.4.ywf07c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
at Request._callback
(/Users/Kyle/.meteor/packages/meteor-tool/.1.1.4.ywf07c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
at Request.self.callback
(/Users/Kyle/.meteor/packages/meteor-tool/.1.1.4.ywf07c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:236:22)
at Request.emit (events.js:98:17)
at Request.<anonymous>
(/Users/Kyle/.meteor/packages/meteor-tool/.1.1.4.ywf07c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1142:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous>
(/Users/Kyle/.meteor/packages/meteor-tool/.1.1.4.ywf07c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1096:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)


Fetching plugin "cordova-plugin-admobpro@2.9.9" via plugin registry
```

I have a package.json file for a mailgun. Does this need to be changed?

I have been trying to figure this out for 4-5 days and help would be appreciated.

**Comment by floatinghotpot** [comment]
It seems that your cordova CLI (called by meteor) still seek the plugin from legacy cordova plugin registry, but in fact it's already migrated to npm repo.

Please upgrade your cordova to 5.x, which will load plugin from npm repo.

**Comment by kylepierce** [comment]
I have upgraded my system to cordova 5.0 (when I type cordova -v) How can I update the cordova called by meteor?

Since I have old cordova plugin's will I need to update all of those to npm?

**Comment by kylepierce** [comment]
Still trying to get it to actually load ads, but seems upgrading to meteor 1.2 fixed the issue.
