### ISSUE TITLE
404 error from cordova.io plugin registry

### ISSUE THREAD

**Issue by fabstao** [floatinghotpot/cordova-admob-pro#272]
Hi!

I´m getting this error:

fabs@host $ cordova plugin add cordova-plugin-admobpro
Fetching plugin "cordova-plugin-admobpro" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-admobpro
npm http 404 http://registry.cordova.io/cordova-plugin-admobpro
Error: 404 Not Found: cordova-plugin-admobpro
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
fabs@host $ 

Is something wrong with Cordova.io?

**Comment by floatinghotpot** [comment]
Your Cordova is out of date, please upgrade to 5.x, it will get plugin from npm repo.

**Comment by fabstao** [comment]
It worked! Thanks!
