### ISSUE TITLE
Crash report from Play Store console

### ISSUE THREAD

**Issue by t-nonque** [floatinghotpot/cordova-admob-pro#290]
Hi, 
I just got a crash report involving the plugin on the Play Store console, here it is:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
	at com.rjfun.cordova.ad.GenericAdPlugin$3.run(GenericAdPlugin.java:386)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6838)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

Thank you by advance ^^

(Android 5.1 Galaxy Core Prime (cprimeltemtr), crosswalk and plugin is 2.10.0)

**Comment by floatinghotpot** [comment]
Thanks for the bug report, looking into it.

Could you please list the plugin versions? 

And, do you use Cordova default webview or Crosswalk?

**Comment by t-nonque** [comment]
I am using crosswalk and plugin is 2.10.0

**Comment by floatinghotpot** [comment]
I am trying to find some clue with a minor changed version, could you please have a re-try?

**Comment by floatinghotpot** [comment]
Just remove the plugin cordova-plugin-admobpro then add it back.

**Comment by floatinghotpot** [comment]
BTW, you need remove both ```cordova-plugin-admobpro``` and its dependency ```cordova-plugin-extension```, and then add ```cordova-plugin-admobpro```.

Any feedback?

**Comment by floatinghotpot** [comment]
As no further info and feedback provided, I assume it has been resolved. Issue closed.
