### ISSUE TITLE
IntelXDK : IOS Build Failed

### ISSUE THREAD

**Issue by a2zbollywood** [floatinghotpot/cordova-admob-pro#308]
I m trying build IOS app through IntelXDK and i got this error when i try to run build option.

My CLI version is 5.1.1 & IOS version is 8. I have attached all the required certificates & provisioning profile.

```
duplicate symbol l017 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADBannerAdViewDelegate.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADRewardBasedVideoAd+Mediation.o)
duplicate symbol l018 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSITimeRecorder.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADRewardBasedVideoAd+Mediation.o)
duplicate symbol l008 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADNativeAdAttributionView.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADPushTransitionView.o)
duplicate symbol l014 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADPinger.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdAppViewController.o)
duplicate symbol l016 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADBannerAdViewDelegate.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADNativeAdImage.o)
duplicate symbol l005 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMWebViewRenderedChecker.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdViewRenderedChecker.o)
duplicate symbol l006 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMWebViewRenderedChecker.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdViewRenderedChecker.o)
duplicate symbol l012 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSI.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSIReporter.o)
duplicate symbol l009 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADInterstitialPool.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdView+VideoAdditions.o)
duplicate symbol l010 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADInterstitialPool.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdView+VideoAdditions.o)
duplicate symbol l022 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADLocation.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMAdapterHTML.o)
duplicate symbol l023 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADLocation.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSIConfiguration.o)
duplicate symbol l016 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADBannerAdViewDelegate.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdNetworkJavaScriptAdViewDelegate.o)
duplicate symbol l017 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADBannerAdViewDelegate.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdNetworkJavaScriptAdViewDelegate.o)
duplicate symbol l002 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAdViewTouchGestureRecognizer.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADAbsoluteTime.o)
duplicate symbol l018 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADCSITimeRecorder.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMRAIDPicture.o)
duplicate symbol l021 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADLocation.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMRAIDResizeProperties.o)
duplicate symbol l022 in:
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADLocation.o)
    mytestapp Downloads/Plugins/cordova-plugin-admobpro/GoogleMobileAds.framework/GoogleMobileAds(GADMRAIDResizeProperties.o)
ld: 28 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld build/mytestapp\ Downloads.build/Release-iphoneos/mytestapp\ Downloads.build/Objects-normal/armv7/mytestapp\ Downloads normal armv7
    cd .../mytestapp/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Developer/android-sdk-macosx/tools:/usr/local/ant/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk -L.../mytestapp/platforms/ios/build/device -L.../mytestapp/platforms/ios/mytestapp\ Downloads/Plugins/cordova-plugin-extension -F.../mytestapp/platforms/ios/build/device -Fmytestapp\ Downloads/Plugins/cordova-plugin-admobpro -filelist .../mytestapp/platforms/ios/build/mytestapp\ Downloads.build/Release-iphoneos/mytestapp\ Downloads.build/Objects-normal/armv7/mytestapp\ Downloads.LinkFileList -dead_strip -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=8.0 -framework AssetsLibrary .../mytestapp/platforms/ios/build/device/libCordova.a -framework CoreGraphics -framework MobileCoreServices -weak_framework SystemConfiguration -weak_framework Social -weak_framework MessageUI -lCordovaGenericAd -framework GoogleMobileAds -framework AdSupport -framework AudioToolbox -framework AVFoundation -framework CoreLocation -framework CoreTelephony -framework EventKit -framework EventKitUI -framework Foundation -framework QuartzCore -framework StoreKit -framework UIKit -Xlinker -dependency_info -Xlinker .../mytestapp/platforms/ios/build/mytestapp\ Downloads.build/Release-iphoneos/mytestapp\ Downloads.build/Objects-normal/armv7/mytestapp\ Downloads_dependency_info.dat -o .../mytestapp/platforms/ios/build/mytestapp\ Downloads.build/Release-iphoneos/mytestapp\ Downloads.build/Objects-normal/armv7/mytestapp\ Downloads

** BUILD FAILED **


The following build commands failed:
    Ld build/mytestapp\ Downloads.build/Release-iphoneos/mytestapp\ Downloads.build/Objects-normal/arm64/mytestapp\ Downloads normal arm64
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,.../mytestapp/platforms/ios/cordova/build-release.xcconfig,-project,mytestapp Downloads.xcodeproj,ARCHS=armv7 armv7s arm64,-target,mytestapp Downloads,-configuration,Release,-sdk,iphoneos,build,VALID_ARCHS=armv7 armv7s arm64,CONFIGURATION_BUILD_DIR=.../mytestapp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=.../mytestapp/platforms/ios/build/sharedpch
Command finished with error code 2: .../mytestapp/platforms/ios/cordova/build --release,--device
ERROR building one of the platforms: Error: .../mytestapp/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: .../mytestapp/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/Developer/cordova/5.1.1/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Process.ChildProcess._handle.onexit (child_process.js:820:5)

```
Please help me

Thank You

**Comment by JuergenRoth** [comment]
same here.

**Comment by a2zbollywood** [comment]
no solution?

**Comment by uedsonsreis** [comment]
I get the same problem.

**Comment by floatinghotpot** [comment]
The very possible reason, if build app with OTHER_LDFLAGS=-all_load, it will cause duplicate symbol conflict. Removing this option will only link symbol being used.

Try contacting XDK team to confirm and then remove this.

**Comment by floatinghotpot** [comment]
Another possible reason is -ObjC option, see:
http://stackoverflow.com/questions/24298144/duplicate-symbols-for-architecture-x86-64
