### ISSUE TITLE
Can't install inmobi sdk for cordova 

### ISSUE THREAD

**Issue by yantian001** [floatinghotpot/cordova-admob-pro#392]
Can't install inmobi sdk for cordova when cordova plugin add cordova-plugin-admob-inmobi ,

**Comment by vintage** [comment]
Here is the output of installing inmobi mediation plugin:

```
cordova plugin add cordova-plugin-admob-inmobi

Installing "cordova-plugin-admob-inmobi" for android
Fetching plugin "com.inmobi.sdk" via npm
Failed to install 'cordova-plugin-admob-inmobi':CordovaError: Failed to fetch plugin com.inmobi.sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.inmobi.sdk
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:192:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Failed to fetch plugin com.inmobi.sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.inmobi.sdk
```

**Comment by alexvandun** [comment]
I was able to install the plugin by opening the plugin.xml and replacing:

<dependency id="com.inmobi.sdk"/>

by

<dependency id="cordova-inmobi-sdk"/>

However I was unable to test if the mediation was working because I keep getting a 'No fill' result when trying to use the interstitial.

@floatinghotpot Is it possible for you to implement this change in the plugin?

**Comment by floatinghotpot** [comment]
just updated the dependency and publish the plugin `cordova-plugin-admob-inmobi`.
