### ISSUE TITLE
Reward Not working! Full example about AdMob.showRewardVideoAd()?

### ISSUE THREAD

**Issue by lucazFerreira** [floatinghotpot/cordova-admob-pro#511]
Sorry my bad english.

How to work with AdMob.showRewardVideoAd()? Could you show a complete example of how to use it?
On my project, banner and intersticial works fine, but Reaward not showing video.
I am newbie on admob, I may have configured it wrong a mediation.
I'm using Vungle, and add Vungle Application ID on Application ID of Mediation AdMob and Vungle Reporting API Key on API Key of Mediation AdMob. Altered status to active on Vungle.

On my code;
`AdMob.prepareRewardVideoAd({
       adId: "my ca-app-pub-xxxx/yyy of admob reaward",
       autoShow: true
   },function(e) {
       alert('SUCCESS ' + e );
       console.log(e);
   }, function(e) {
       alert('FAIL ' + e);
       console.log(e);
   });`

Aways show alert "SUCESS OK"

On next line:
`AdMob.showRewardVideoAd();`

Nothing show.

**Comment by floatinghotpot** [comment]
Usually, it will take a few seconds (or longer) for the AdMob SDK to download ad resource (video stream) in the background.

As you set param `autoShow: true` when calling prepareRewardVideoAd(), no need call showRewardVideoAd().

Most important, as you are using mediation to vungle, you need add the admob-vungle mediation adapter to you project before building app.

**Comment by lucazFerreira** [comment]
Hm, I don't added vungle mediation.
So, I'm trying `cordova plugin add cordova-plugin-admob-vungle` and get response:
> Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-plugin-admob-vungle

Can you help me?

**Comment by floatinghotpot** [comment]
There is not adapter plugin named cordova-plugin-admob-vungle yet.

I will try creating one.

**Comment by huynhvantuan** [comment]
Hi @floatinghotpot,
I've same error when use AdMob.showRewardVideoAd.

<img width="940" alt="screen shot 2017-02-27 at 10 07 57 am" src="https://cloud.githubusercontent.com/assets/11658028/23347534/8bb0160c-fcd5-11e6-84bb-f8939d1f179b.png">
<img width="973" alt="screen shot 2017-02-27 at 10 08 19 am" src="https://cloud.githubusercontent.com/assets/11658028/23347535/8c25eb84-fcd5-11e6-8ede-fc746bc4f6f2.png">

use: 
function prepareRewardedVideoAds() {
    AdMob.prepareRewardVideoAd({
        adId: admobid.rewarded,
        isTesting: true, // TODO: remove this line when release
        autoShow: false
    },function (e) {
        alert("success ");
    }, function (ex) {
        alert("error ");
    });
}

function showRewardedVideoAds() {
    if (AdMob) AdMob.showRewardVideoAd();
}

 and start prepareRewarded has alert "success" but when invoke showRewardedVideoAds function, alway get: error 9 "no ad returned from any ad server"; included: testing on mac And on Testflight. iphone 6s -  ios 10
- in admob config, i use only Admob Network (above image) - > is my Admob Config  incorrect? or I must add multiple New Ad Networks (like: Adcolony, vungle,... ) and  if when i add them, i not found any  plugin use in phonegap.
p/s: sorry my english.
Thanks in advance.

**Comment by huynhvantuan** [comment]
any suggestions !!!

**Comment by sava999** [comment]
Hi All,

First of all thanks for great plugins and all hard work you are putting into this.

I am having similar problem as @huynhvantuan, I can't make reward video ad to show. I am using Ionic 2 framework, and my code is next.

```
import { AdMob } from 'ionic-native';

... // some not important code

/*
 * Method called on button click
 */
showAd() {

    AdMob.getAdSettings().then((data) => {
      console.log(JSON.stringify(data));
    });

    AdMob.prepareRewardVideoAd({
        adId: 'ca-app-pub-2182503134198201/6453314378',
        isTesting: true,
        autoShow: true
    }).then(
      (data) => {
        console.log('showing add');
        console.log(JSON.stringify(data));
        // AdMob.showRewardVideoAd();
      },

      (error) => {
        console.log('Ad failed');
        console.log(JSON.stringify(error));
      }
    );
}
```

In xCode I am getting next:

```
2017-02-27 12:37:30.353483 TravelMate[480:73233] prepareRewardVideoAd
2017-02-27 12:37:30.451545 TravelMate[480:73233] {"adId":"B1275060-F76E-4C4C-81EF-4B17D4467CA3","adTrackingEnabled":true}
2017-02-27 12:37:30.451681 TravelMate[480:73233] showing add
2017-02-27 12:37:30.451758 TravelMate[480:73233] null
2017-02-27 12:37:30.451817 TravelMate[480:73233] showRewardVideoAd
2017-02-27 12:37:30.732858 TravelMate[480:73358] WF: === Starting WebFilter logging for process TravelMate
2017-02-27 12:37:30.733824 TravelMate[480:73358] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2017-02-27 12:37:30.734913 TravelMate[480:73358] WF: _WebFilterIsActive returning: NO
2017-02-27 12:37:31.104549 TravelMate[480:73803] <Google:HTML> You are currently using version 7.16.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.
2017-02-27 12:37:31.176874 TravelMate[480:73233] AdMob, onAdFailLoad, {'adNetwork':'AdMob','adType':'rewardvideo','adEvent':'onAdFailLoad','error':1,'reason':'Request Error: No ad to show.'}
```

And for Android in logcat I am getting next:

```
02-27 12:51:18.917 12486 12486 D CordovaWebViewImpl: >>> loadUrl(javascript:(function(){try{window.adlicAppId='com.travelmateapp.travelmate';}catch(e){};})();)
02-27 12:51:19.468 12486 12609 D GenericAdPlugin: prepareRewardVideoAd: ca-app-pub-2182503134198201/6453314378, true
02-27 12:51:19.468 12486 12609 W PluginManager: THREAD WARNING: exec() call to AdMob.prepareRewardVideoAd blocked the main thread for 578ms. Plugin should use CordovaInterface.getThreadPool().
02-27 12:51:19.496 12486 12609 D GenericAdPlugin: showRewardVideoAd
02-27 12:51:19.572 12486 12486 W System  : ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000009/n/armeabi
02-27 12:51:19.577 12486 12486 D DynamitePackage: Instantiated singleton DynamitePackage.
02-27 12:51:19.577 12486 12486 D DynamitePackage: Instantiating com.google.android.gms.ads.reward.ChimeraRewardedVideoAdCreatorImpl
02-27 12:51:19.648 12486 12913 I DynamiteModule: Considering local module com.google.android.gms.piccard.dynamite:0 and remote module com.google.android.gms.piccard.dynamite:12
02-27 12:51:19.648 12486 12913 I DynamiteModule: Selected remote version of com.google.android.gms.piccard.dynamite, version >= 12
02-27 12:51:19.665 12486 12913 W System  : ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000009/n/armeabi
02-27 12:51:19.719 12486 12486 I Ads     : Starting ad request.
02-27 12:51:19.721 12486 12486 I Ads     : Use AdRequest.Builder.addTestDevice("2D9B3E0DFF932F18A1EEF271727A3CE5") to get test ads on this device.
02-27 12:51:19.739 12486 12486 D SystemWebChromeClient: http://192.168.0.20:8100/__ion-dev-server/ion-dev.js?v=1.0.0: Line 156 : {"adId":"d3c08979-572f-42f7-a2c5-30bed3a3a922","adTrackingEnabled":true}
02-27 12:51:19.739 12486 12486 I chromium: [INFO:CONSOLE(156)] "{"adId":"d3c08979-572f-42f7-a2c5-30bed3a3a922","adTrackingEnabled":true}", source: http://192.168.0.20:8100/__ion-dev-server/ion-dev.js?v=1.0.0 (156)
02-27 12:51:19.739 12486 12486 D SystemWebChromeClient: http://192.168.0.20:8100/__ion-dev-server/ion-dev.js?v=1.0.0: Line 156 : showing add
02-27 12:51:19.739 12486 12486 I chromium: [INFO:CONSOLE(156)] "showing add", source: http://192.168.0.20:8100/__ion-dev-server/ion-dev.js?v=1.0.0 (156)
02-27 12:51:19.739 12486 12486 D SystemWebChromeClient: http://192.168.0.20:8100/__ion-dev-server/ion-dev.js?v=1.0.0: Line 156 : "OK"
02-27 12:51:19.739 12486 12486 I chromium: [INFO:CONSOLE(156)] ""OK"", source: http://192.168.0.20:8100/__ion-dev-server/ion-dev.js?v=1.0.0 (156)
02-27 12:51:19.976  1506  1855 W GCoreFlp: No location to return for getLastLocation()
02-27 12:51:19.977  1960  1960 W Ads     : Location is not available. Returning null
02-27 12:51:20.064  1960  2934 W Herrevad: [174] shz.b: Invalid mccmnc 
02-27 12:51:20.065  1960  2934 W Herrevad: [174] shz.b: Invalid mccmnc 
02-27 12:51:20.118   623  9617 D NetlinkSocketObserver: NeighborEvent{elapsedMs=10099712, 192.168.0.1, [481D708C14A1], RTM_NEWNEIGH, NUD_REACHABLE}
02-27 12:51:20.708 12486 12913 W Ads     : Fail to instantiate adapter com.google.DummyAdapter
02-27 12:51:20.708 12486 12913 W Ads     : android.os.RemoteException
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.internal.zzjz.zzav(Unknown Source)
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.internal.zzjz.zzau(Unknown Source)
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.internal.zzjz.zzas(Unknown Source)
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.internal.zzka$zza.onTransact(Unknown Source)
02-27 12:51:20.708 12486 12913 W Ads     : 	at android.os.Binder.transact(Binder.java:387)
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.ads.internal.mediation.client.d.a(:com.google.android.gms.DynamiteModulesA:94)
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.ads.internal.reward.c.b(:com.google.android.gms.DynamiteModulesA:229)
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.ads.internal.reward.mediation.k.a(:com.google.android.gms.DynamiteModulesA:1140)
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.DynamiteModulesA:19)
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.ads.internal.util.ab.call(:com.google.android.gms.DynamiteModulesA:1055)
02-27 12:51:20.708 12486 12913 W Ads     : 	at com.google.android.gms.ads.internal.util.ac.run(:com.google.android.gms.DynamiteModulesA:75)
02-27 12:51:20.708 12486 12913 W Ads     : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
02-27 12:51:20.708 12486 12913 W Ads     : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-27 12:51:20.708 12486 12913 W Ads     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-27 12:51:20.708 12486 12913 W Ads     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-27 12:51:20.708 12486 12913 W Ads     : 	at java.lang.Thread.run(Thread.java:818)
02-27 12:51:20.709 12486 12486 W Ads     : Failed to load ad: 3
02-27 12:51:20.710 12486 12486 D GenericAdPlugin: AdMob, onAdFailLoad, {'adNetwork':'AdMob','adType':'rewardvideo','adEvent':'onAdFailLoad','error':3,'reason':'No fill'}
02-27 12:51:20.710 12486 12486 D CordovaWebViewImpl: >>> loadUrl(javascript:cordova.fireDocumentEvent('onAdFailLoad',{'adNetwork':'AdMob','adType':'rewardvideo','adEvent':'onAdFailLoad','error':3,'reason':'No fill'});)

```

So on iOS I have error "Request Error: No ad to show." and on Android "No fill", which is strange since `isTesting` is set to `true`. I guess I made some config issue but I can't figure out what. Please note that banner and interstitial ads are working fine.

I appreciate any help. Thank you

**Comment by floatinghotpot** [comment]
Before using Vungle mediation, you can try reward video from  AdMob itself. 

Here are 2 test ad unit ids provided by admob team:
https://groups.google.com/forum/#!msg/google-admob-ads-sdk/k-kVwVu2XBc/fgWFiu62BQAJ

For Reward Videos, the following are our test Ad Unit ID
*  iOS: ca-app-pub-3940256099942544/1712485313
*  Android: ca-app-pub-3940256099942544/5224354917

Note that Reward Video Ad Unit IDs are platform specific.

**Comment by HeosS** [comment]
Hello, 
implement the plugin in phonegap build and the first time shows the video rewarded but the second time no. What can be caused this?

**Comment by lucazFerreira** [comment]
@floatinghotpot, thanks for help! using reward Admob, I`m getting same problem the HeosS. Any idea?

**Comment by floatinghotpot** [comment]
It should have been fixed. please make sure:
1. you are using the latest version of plugin.
2. call prepareRewardVideoAd() before every calling to showRewardVideoAd().

**Comment by lucazFerreira** [comment]
Thanks @floatinghotpot !! Reward video from AdMob working fine! My plugin was outdated.
