### ISSUE TITLE
Many crashes reports: java.lang.NullPointerException

### ISSUE THREAD

**Issue by tominou** [floatinghotpot/cordova-admob-pro#559]
Here is the full report

> java.lang.NullPointerException: 
  at com.rjfun.cordova.admob.AdMobPlugin.getAdViewSize(AdMobPlugin.java:185)
  at com.rjfun.cordova.admob.AdMobPlugin.__getAdViewWidth(AdMobPlugin.java:191)
  at com.rjfun.cordova.ad.GenericAdPlugin$5.run(GenericAdPlugin.java:582)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:158)
  at android.app.ActivityThread.main(ActivityThread.java:7229)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by magickaito** [comment]
Same issue here, my trace:
```
java.lang.NullPointerException: 
  at android.webkit.WebViewClassic.loadUrlImpl(WebViewClassic.java:2771)
  at android.webkit.WebViewClassic.loadUrlImpl(WebViewClassic.java:2787)
  at android.webkit.WebViewClassic.loadUrl(WebViewClassic.java:2780)
  at android.webkit.WebView.loadUrl(WebView.java:843)
  at org.apache.cordova.engine.SystemWebViewEngine.loadUrl(SystemWebViewEngine.java:268)
  at org.apache.cordova.CordovaWebViewImpl.loadUrlIntoView(CordovaWebViewImpl.java:129)
  at org.apache.cordova.CordovaWebViewImpl.loadUrl(CordovaWebViewImpl.java:198)
  at com.rjfun.cordova.ext.CordovaPluginExt.fireEvent(CordovaPluginExt.java:69)
  at com.rjfun.cordova.ad.GenericAdPlugin.fireEvent(GenericAdPlugin.java:221)
  at com.rjfun.cordova.ad.GenericAdPlugin.fireAdErrorEvent(GenericAdPlugin.java:764)
  at com.rjfun.cordova.admob.AdMobPlugin.access$200(AdMobPlugin.java:35)
  at com.rjfun.cordova.admob.AdMobPlugin$BannerListener.onAdFailedToLoad(AdMobPlugin.java:500)
  at com.google.android.gms.ads.internal.client.zzc.onAdFailedToLoad(Unknown Source:0)
  at com.google.android.gms.ads.internal.client.zzq$zza.onTransact(Unknown Source:0)
  at android.os.Binder.transact(Binder.java:310)
  at com.google.android.gms.ads.internal.client.z.a(:com.google.android.gms.DynamiteModulesA:124)
  at com.google.android.gms.ads.internal.a.a(:com.google.android.gms.DynamiteModulesA:872)
  at com.google.android.gms.ads.internal.a.b(:com.google.android.gms.DynamiteModulesA:424)
  at com.google.android.gms.ads.internal.c.b(:com.google.android.gms.DynamiteModulesA:164)
  at com.google.android.gms.ads.internal.m.run(:com.google.android.gms.DynamiteModulesA:150)
  at android.os.Handler.handleCallback(Handler.java:800)
  at android.os.Handler.dispatchMessage(Handler.java:100)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5476)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:525)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
  at dalvik.system.NativeStart.main(Native Method:0)
```

**Comment by floatinghotpot** [comment]
Could you please give more details, version of cordova, plugin, android?

And, did you use some other plugins at the same time?
