### ISSUE TITLE
Error: Uncaught (in promise): null

### ISSUE THREAD

**Issue by enzonotario** [floatinghotpot/cordova-admob-pro#569]
Hi! I'm using this library in an ionic 3 app and it works perfectly with banners and intersticial ads, but with reward videos it doesn't works.
The only code that I run is:

```this.admob.prepareRewardVideoAd(this.admobId.rewardVideo);```

And it causes the next error (note that I only prepare the reward video ad, I don't show it):

```
"Error: Uncaught (in promise): null
    at new Error (native)
    at Error.d (http://192.168.1.3:8100/build/polyfills.js:3:3991)
    at l (http://192.168.1.3:8100/build/polyfills.js:3:3244)
    at http://192.168.1.3:8100/build/polyfills.js:3:2600
    at Object.cordova.callbackFromNative (http://192.168.1.3:8100/cordova.js:295:52)
    at processMessage (http://192.168.1.3:8100/cordova.js:1119:17)
    at processMessages (http://192.168.1.3:8100/cordova.js:1142:9)
    at t.invoke (http://192.168.1.3:8100/build/polyfills.js:3:11562)
    at Object.inner.inner.fork.onInvoke (http://192.168.1.3:8100/build/main.js:4623:37)
    at t.invoke (http://192.168.1.3:8100/build/polyfills.js:3:11502)
    at n.run (http://192.168.1.3:8100/build/polyfills.js:3:6468)
    at http://192.168.1.3:8100/build/polyfills.js:3:3767
    at t.invokeTask (http://192.168.1.3:8100/build/polyfills.js:3:12256)
    at Object.inner.inner.fork.onInvokeTask (http://192.168.1.3:8100/build/main.js:4614:37)
    at t.invokeTask (http://192.168.1.3:8100/build/polyfills.js:3:12177)"
```

And, of course, if I try to show the reward video ad, it doesn't works too.

```
this.admob.prepareRewardVideoAd(this.admobId.rewardVideo).then(() => {
    this.admob.showRewardVideoAd();
});
```

The above code gives me the same error.

Well, if I caught the promise error, it shows me, of course, ```null```
It's in the same place where the banner and intersticial works.

Can anyone help me, please?

Sorry for my english.

Thanks!

**Comment by floatinghotpot** [comment]
Be very careful when using `this`. It depends on your context. 

It's better to use closure, assign to a variable.
```javascript
var me = this;
me.admob.prepareRewardVideoAd(me.admobId.rewardVideo).then(() => {
    me.admob.showRewardVideoAd();
});
```

**Comment by enzonotario** [comment]
Thanks so much for your reply!

But I can't get it work with your advice

My code is:
```
var me = this;

me.platform.ready().then(() => {
  if (me.platform.is('android')) {
    me.admobId = {
      banner: 'xxx',
      intersticial: 'xxx',
      rewardVideo: 'xxx',
    };
  }

  me.admob.createBanner(me.admobId.banner);

  me.admob.prepareRewardVideoAd(me.admobId.rewardVideo).then(() => {
    me.admob.showRewardVideoAd();
  }, (errors) => {
    console.error('reward video', errors);
  });
});
```

The banner still works, but the reward video still gives me an ```null``` error

Do you know where is the problem?

Thanks again!

**Comment by floatinghotpot** [comment]
Try use `AdMob.prepareRewardVideoAd()` instead of `this.admob` or `me.admob`.

Here is a tutorial, by Nic Raboy.
[Monetize With Google Admob In An Ionic 2 Mobile App](https://www.thepolyglotdeveloper.com/2016/02/monetize-google-admob-ionic-2-mobile-app/)

**Comment by enzonotario** [comment]
Amazing! It's the solution! Thanks so much!
